version: 2.1

# this allows you to use CircleCI's dynamic configuration feature
setup: true

# the continuation orb is required in order to use dynamic configuration
orbs:
  node: circleci/node@5.1.0
  continuation: circleci/continuation@0.1.2

# our defined job, and its steps
jobs:
  generate-config:
    executor:
      name: node/default
    steps:
      - checkout # checkout code
      - node/install-packages:
          override-ci-command: npm run ci:clean-install
          cache-version: setup-v1
      - run: # run a command
          name: Generate config
          command: |
            node ./tools/circleci/generate-config.mjs ./.circleci/generated_config.yml
      - persist_to_workspace:
          root: .
          paths:
            - '.circleci'
  setup:
    executor: continuation/default
    steps:
      - attach_workspace:
          at: .
      - continuation/continue:
          configuration_path: ./.circleci/generated_config.yml # use newly generated config to continue

# our single workflow, that triggers the setup job defined above
workflows:
  setup:
    jobs:
      - generate-config
      - setup: 
          requires:
            - generate-config
