name: Feature request
description: Suggest a feature
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: dropdown
    id: plugin
    attributes:
      label: Plugin
      description: What plugin is concerned ?
      options: ["@knodes/typedoc-pluginutils", "@knodes/typedoc-plugin-pages", "@knodes/typedoc-plugin-code-blocks", Unspecified] # !FORMAT options: [${...plugins}, Unspecified]
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: What would you want ?
      placeholder: "Example: When doing X, I would like that Y happens."
    validations:
      required: true